// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Collection    string                 `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	RequestName   string                 `protobuf:"bytes,6,opt,name=request_name,json=requestName,proto3" json:"request_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RequestData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RequestData) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RequestData) GetRequestName() string {
	if x != nil {
		return x.RequestName
	}
	return ""
}

type HeaderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderList) Reset() {
	*x = HeaderList{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderList) ProtoMessage() {}

func (x *HeaderList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderList.ProtoReflect.Descriptor instead.
func (*HeaderList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]*HeaderList `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseData) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResponseData) GetHeaders() map[string]*HeaderList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ResponseData) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type HookContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RequestData           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *ResponseData          `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigJson    []byte                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	Workspace     string                 `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookContext) Reset() {
	*x = HookContext{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookContext) ProtoMessage() {}

func (x *HookContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookContext.ProtoReflect.Descriptor instead.
func (*HookContext) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookContext) GetRequest() *RequestData {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *HookContext) GetResponse() *ResponseData {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *HookContext) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *HookContext) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *HookContext) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Hooks         []string               `protobuf:"bytes,4,rep,name=hooks,proto3" json:"hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookType      string                 `protobuf:"bytes,1,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"`
	Context       *HookContext           `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HookRequest) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *HookRequest) GetContext() *HookContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *HookContext           `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HookResponse) GetContext() *HookContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *HookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x05proto\"\x85\x02\n" +
	"\vRequestData\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\aheaders\x18\x03 \x03(\v2\x1f.proto.RequestData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1e\n" +
	"\n" +
	"collection\x18\x05 \x01(\tR\n" +
	"collection\x12!\n" +
	"\frequest_name\x18\x06 \x01(\tR\vrequestName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\n" +
	"HeaderList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x82\x02\n" +
	"\fResponseData\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12:\n" +
	"\aheaders\x18\x03 \x03(\v2 .proto.ResponseData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x1aM\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.HeaderListR\x05value:\x028\x01\"\xb2\x02\n" +
	"\vHookContext\x12,\n" +
	"\arequest\x18\x01 \x01(\v2\x12.proto.RequestDataR\arequest\x12/\n" +
	"\bresponse\x18\x02 \x01(\v2\x13.proto.ResponseDataR\bresponse\x12E\n" +
	"\venvironment\x18\x03 \x03(\v2#.proto.HookContext.EnvironmentEntryR\venvironment\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\fR\n" +
	"configJson\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05hooks\x18\x04 \x03(\tR\x05hooks\"X\n" +
	"\vHookRequest\x12\x1b\n" +
	"\thook_type\x18\x01 \x01(\tR\bhookType\x12,\n" +
	"\acontext\x18\x02 \x01(\v2\x12.proto.HookContextR\acontext\"R\n" +
	"\fHookResponse\x12,\n" +
	"\acontext\x18\x01 \x01(\v2\x12.proto.HookContextR\acontext\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\a\n" +
	"\x05Empty2l\n" +
	"\x06Plugin\x12*\n" +
	"\aGetInfo\x12\f.proto.Empty\x1a\x11.proto.PluginInfo\x126\n" +
	"\vExecuteHook\x12\x12.proto.HookRequest\x1a\x13.proto.HookResponseB3Z1github.com/petitorium/petitorium-plugin-sdk/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plugin_proto_goTypes = []any{
	(*RequestData)(nil),  // 0: proto.RequestData
	(*HeaderList)(nil),   // 1: proto.HeaderList
	(*ResponseData)(nil), // 2: proto.ResponseData
	(*HookContext)(nil),  // 3: proto.HookContext
	(*PluginInfo)(nil),   // 4: proto.PluginInfo
	(*HookRequest)(nil),  // 5: proto.HookRequest
	(*HookResponse)(nil), // 6: proto.HookResponse
	(*Empty)(nil),        // 7: proto.Empty
	nil,                  // 8: proto.RequestData.HeadersEntry
	nil,                  // 9: proto.ResponseData.HeadersEntry
	nil,                  // 10: proto.HookContext.EnvironmentEntry
}
var file_plugin_proto_depIdxs = []int32{
	8,  // 0: proto.RequestData.headers:type_name -> proto.RequestData.HeadersEntry
	9,  // 1: proto.ResponseData.headers:type_name -> proto.ResponseData.HeadersEntry
	0,  // 2: proto.HookContext.request:type_name -> proto.RequestData
	2,  // 3: proto.HookContext.response:type_name -> proto.ResponseData
	10, // 4: proto.HookContext.environment:type_name -> proto.HookContext.EnvironmentEntry
	3,  // 5: proto.HookRequest.context:type_name -> proto.HookContext
	3,  // 6: proto.HookResponse.context:type_name -> proto.HookContext
	1,  // 7: proto.ResponseData.HeadersEntry.value:type_name -> proto.HeaderList
	7,  // 8: proto.Plugin.GetInfo:input_type -> proto.Empty
	5,  // 9: proto.Plugin.ExecuteHook:input_type -> proto.HookRequest
	4,  // 10: proto.Plugin.GetInfo:output_type -> proto.PluginInfo
	6,  // 11: proto.Plugin.ExecuteHook:output_type -> proto.HookResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
